### ISSUE TITLE
Icons are not working, a empty placeholder shows

### ISSUE THREAD

**Issue by tariksalihovic** [NikSWE/flutter_brand_icons#2]
Hi after installing this package and using the icons, it does not show the Icons e.g. BrandIcons.apple - logo of apple, it only shows a empty placeholder where there should be a logo instead.

**Comment by gopalkohli** [comment]
Please try:

Stopping the app
Running flutter clean in your app directory
Deleting the app from your simulator / emulator / device
Rebuild & Deploy the app.
